nginx:
    image: nginx:1.13.3
    volumes:
    - ./config/nginx-docker.conf:/etc/nginx/nginx.conf
    volumes_from:
    - php
    links:
    - php
    ports:
    - 80:80
php:
    image: php:7-fpm
    links:
    - mysql
    volumes:
    - ./:/var/www/html/
mysql:
    image: mariadb
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=spoty
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    volumes:
    - my-datavolume:/var/lib/mysql
